# Here shows the count method

First, Import necessary library

In [1]:
import numpy as np
import pandas as pd
import io
import folium # map rendering library
import matplotlib.cm as cm
import matplotlib.colors as colors

Next, import the dataset and combine it into one

In [2]:
lists_0=pd.read_csv(r'grouped_lists_0.csv')
lists_1=pd.read_csv(r'grouped_lists_1.csv')
lists_2=pd.read_csv(r'grouped_lists_2.csv')
lists_3=pd.read_csv(r'grouped_lists_3.csv')
lists_4=pd.read_csv(r'grouped_lists_4.csv')
lists_1

,Unnamed: 0,Building name,Related probable/confirmed cases,count,lat_col,long_col
0,236,"Chun Yu House, Sam Shing Estate",4455,1,22.381214,113.978212
1,237,"Chung Kam House, Tin Chun Court",4171,1,37.300334,99.021896
2,238,"Chung Kam House, Tin Chung Court","3744, 3905",2,22.460450,114.000154
3,239,Chung Kin Building,4159,1,22.322871,114.160516
4,240,"Chung Lau House, Tin Chung Court","3793, 3934",2,22.460450,114.000154
...,...,...,...,...,...,...
231,467,Indi home Green River Restaurant,4413,1,NaN,NaN
232,468,Indi home Maxim's MX,4413,1,NaN,NaN
233,469,Island Lodge,4283,1,22.292321,114.201738
234,470,Java Road Municipal Services Building,"2299, 2468",2,22.292333,114.199354
235,471,K-point,4412,1,50.462775,30.504672

In [3]:
rawdata = pd.concat([lists_0,lists_1,lists_2,lists_3,lists_4])
rawdata

,Unnamed: 0,Building name,Related probable/confirmed cases,count,lat_col,long_col,Unnamed: 0.1
0,0,1 Fu Chi Path,"1831, 2113, 3830",3,22.335799,114.207887,NaN
1,1,1 Hung To Road No. 1 Hung To Canteen,"4186, 4387",2,NaN,NaN,NaN
2,2,1 Wing Lung Street,4442,1,22.337019,114.157718,NaN
3,3,12 Po Peng Street,4338,1,3.811276,103.323790,NaN
4,4,12 Tai Hing Tai Road,4119,1,22.205907,114.027745,NaN
...,...,...,...,...,...,...,...
231,1175,"Yuk King House, King Ming Court","4297, 4298",2,22.323272,114.249775,1175.0
232,1176,"Yuk Mei House, Yau Chui Court","3694, 3908",2,22.300251,114.238107,1176.0
233,1177,Zone B Tai Po Mega Mall,"2991, 3504",2,NaN,NaN,1177.0
234,1178,iSQUARE,"3941, 4001",2,22.296778,114.171876,1178.0
235,1179,iclub Mong Kok Hotel,4073,1,22.320293,114.165219,1179.0

In the followings, perform filtering to remove location without well defined coordinate, either is NaN value or the coordinate is outsite of Hong Kong region.

In [4]:
rawdata = rawdata.dropna()
#HK lands departments
#Hong Kong Special Administrative Region lies between Latitude 22Â°08' North and 22Â°35' North, Longitude 113Â°49' East and 114Â°31' East
#remove coordinates not lies in Hong Kong 22<latitute<23, 113<longitude<115
rawdata = rawdata[rawdata.lat_col >22]
rawdata = rawdata[rawdata.lat_col <23]
rawdata = rawdata[rawdata.long_col >113]
rawdata = rawdata[rawdata.long_col <115]
rawdata

,Unnamed: 0,Building name,Related probable/confirmed cases,count,lat_col,long_col,Unnamed: 0.1
0,472,K11 MUSEA,"3369, 3441",2,22.294416,114.174843,472.0
3,475,"Ka Chun House, Ka Lung Court",3849,1,22.249281,114.138037,475.0
4,476,"Ka Lei Lau, Ka Wai Chuen","4425, 4549, 4550, 4551",4,22.307993,114.186726,476.0
6,478,"Kai Him Lau, Cho Yiu Chuen",4457,1,22.346710,114.127505,478.0
7,479,"Kai Ning House, Kai Yip Estate",3701,1,22.329837,114.209912,479.0
...,...,...,...,...,...,...,...
230,1174,"Yuet Wing House, Tin Yuet Estate","4288, 4510",2,22.462994,113.999735,1174.0
231,1175,"Yuk King House, King Ming Court","4297, 4298",2,22.323272,114.249775,1175.0
232,1176,"Yuk Mei House, Yau Chui Court","3694, 3908",2,22.300251,114.238107,1176.0
234,1178,iSQUARE,"3941, 4001",2,22.296778,114.171876,1178.0
235,1179,iclub Mong Kok Hotel,4073,1,22.320293,114.165219,1179.0

Sort the dataframe based on count value, then list out the top 10 building having the most count value.

In [5]:
rawdata_sort= rawdata.sort_values(by=['count'],ascending=False)
rawdata_sort = rawdata_sort[0:10]
rawdata_sort

,Unnamed: 0,Building name,Related probable/confirmed cases,count,lat_col,long_col,Unnamed: 0.1
112,1056,Tsz Wan Shan Shopping Centre,"1311, 1312, 1404, 1444, 1477, 1491, 1507, 1508...",83,22.348022,114.200591,1056.0
203,1147,Yee On Court,"2289, 2476, 2546, 2722, 3102, 3154, 3165, 3205...",35,22.320446,114.176428,1147.0
46,754,Pei Ho Street Municipal Services Building,"1557, 1608, 1611, 1808, 1852, 1905, 1926, 1927...",21,22.329372,114.160930,754.0
120,828,Shek Wu Hui Municipal Services Building,"1947, 1989, 2053, 2072, 2179, 2284, 2393, 2576...",18,22.501996,114.130550,828.0
231,704,Ngau Chi Wan Municipal Services Building,"1371, 1388, 1389, 1394, 1467, 1468, 1523, 1597...",17,22.334496,114.208999,704.0
209,1153,Yeung Uk Road Municipal Services Building,"1652, 1859, 2196, 2261, 2239, 3047, 3117, 3244...",17,22.368976,114.114582,1153.0
207,680,Millennium City 3,"2396, 2434, 2535, 2635, 2720, 2742, 2811, 2822...",16,22.314527,114.219643,680.0
97,805,San Hui Market,"1471, 1561, 1907, 1931, 2154, 2381, 2458, 2493...",15,22.396796,113.976546,805.0
190,898,TKO Gateway,"1590, 1983, 2123, 2330, 2479, 2572, 2670, 3245...",13,22.317220,114.266417,898.0
66,538,Kwai Chung Plaza,"1820, 1996, 2332, 2455, 2459, 2465, 2602, 3018...",12,22.358099,114.127636,538.0

Plot the data in map. The Hong Kong base map is used and each point is drawn in blue circle where the radius is the count value divided by 2. This map shows the top 10 buildings where cases mostly occurs. 
a html file count.html is saved for further view on the cases.

In [8]:
latitude =22.329
longitude = 114.169
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# add markers to the map
for lat, lon, poi,count in zip(rawdata_sort['lat_col'], rawdata_sort['long_col'], rawdata_sort['Building name'],rawdata_sort['count']):
    label = folium.Popup(str(poi), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=count/2,
        popup=label,
        fill=True,
        fill_opacity=0.7).add_to(map_clusters)
    
map_clusters.save('count.html')
map_clusters